package org.aepscolombia.platform.models.entity;
// Generated Apr 8, 2014 9:37:27 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ActionsValues generated by hbm2java
 */
@Entity
@Table(name="actions_values"
    ,catalog="madr_bd13"
    , uniqueConstraints = @UniqueConstraint(columnNames="key_act_val") 
)
public class ActionsValues  implements java.io.Serializable {


     private Integer idActVal;
     private String keyActVal;
     private String esEs;
     private String enEn;

    public ActionsValues() {
    }

	
    public ActionsValues(String keyActVal) {
        this.keyActVal = keyActVal;
    }
    public ActionsValues(String keyActVal, String esEs, String enEn) {
       this.keyActVal = keyActVal;
       this.esEs = esEs;
       this.enEn = enEn;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_act_val", unique=true, nullable=false)
    public Integer getIdActVal() {
        return this.idActVal;
    }
    
    public void setIdActVal(Integer idActVal) {
        this.idActVal = idActVal;
    }
    
    @Column(name="key_act_val", unique=true, nullable=false, length=50)
    public String getKeyActVal() {
        return this.keyActVal;
    }
    
    public void setKeyActVal(String keyActVal) {
        this.keyActVal = keyActVal;
    }
    
    @Column(name="es_es", length=50)
    public String getEsEs() {
        return this.esEs;
    }
    
    public void setEsEs(String esEs) {
        this.esEs = esEs;
    }
    
    @Column(name="en_en", length=50)
    public String getEnEn() {
        return this.enEn;
    }
    
    public void setEnEn(String enEn) {
        this.enEn = enEn;
    }




}


