package org.aepscolombia.platform.models.entity;
// Generated Apr 8, 2014 9:37:27 AM by Hibernate Tools 3.2.1.GA

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AmendmentsFertilizers generated by hbm2java
 */
@Entity
@Table(name="amendments_fertilizers"
    ,catalog="madr_bd13"
)
public class AmendmentsFertilizers  implements java.io.Serializable {


     private Integer idAmeFer;
     private String nameAmeFer;
     private Boolean statusAmeFer;

    public AmendmentsFertilizers() {
    }

    public AmendmentsFertilizers(String nameAmeFer, Boolean statusAmeFer) {
       this.nameAmeFer = nameAmeFer;
       this.statusAmeFer = statusAmeFer;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_ame_fer", unique=true, nullable=false)
    public Integer getIdAmeFer() {
        return this.idAmeFer;
    }
    
    public void setIdAmeFer(Integer idAmeFer) {
        this.idAmeFer = idAmeFer;
    }
    
    @Column(name="name_ame_fer", length=45)
    public String getNameAmeFer() {
        return this.nameAmeFer;
    }
    
    public void setNameAmeFer(String nameAmeFer) {
        this.nameAmeFer = nameAmeFer;
    }
    
    @Column(name="status_ame_fer")
    public Boolean getStatusAmeFer() {
        return this.statusAmeFer;
    }
    
    public void setStatusAmeFer(Boolean statusAmeFer) {
        this.statusAmeFer = statusAmeFer;
    }
    
}


