package org.aepscolombia.platform.models.entity;
// Generated Jan 21, 2014 11:35:29 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AmendmentsFertilizations generated by hbm2java
 */
@Entity
@Table(name="amendments_fertilizations"
    ,catalog="madr_bd11"
)
public class AmendmentsFertilizations  implements java.io.Serializable {


     private Integer idAmeFer;
     private Fertilizations fertilizations;
     private AmendmentsFertilizers amendmentsFertilizers;
     private String otherProductAmeFer;

    public AmendmentsFertilizations() {
    }

	
    public AmendmentsFertilizations(Fertilizations fertilizations) {
        this.fertilizations = fertilizations;
    }
    public AmendmentsFertilizations(Fertilizations fertilizations, AmendmentsFertilizers amendmentsFertilizers, String otherProductAmeFer) {
       this.fertilizations = fertilizations;
       this.amendmentsFertilizers = amendmentsFertilizers;
       this.otherProductAmeFer = otherProductAmeFer;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_ame_fer", unique=true, nullable=false)
    public Integer getIdAmeFer() {
        return this.idAmeFer;
    }
    
    public void setIdAmeFer(Integer idAmeFer) {
        this.idAmeFer = idAmeFer;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_fertilization_ame_fer", nullable=false)
    public Fertilizations getFertilizations() {
        return this.fertilizations;
    }
    
    public void setFertilizations(Fertilizations fertilizations) {
        this.fertilizations = fertilizations;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_product_ame_fer")
    public AmendmentsFertilizers getAmendmentsFertilizers() {
        return this.amendmentsFertilizers;
    }
    
    public void setAmendmentsFertilizers(AmendmentsFertilizers amendmentsFertilizers) {
        this.amendmentsFertilizers = amendmentsFertilizers;
    }
    
    @Column(name="other_product_ame_fer", length=65535)
    public String getOtherProductAmeFer() {
        return this.otherProductAmeFer;
    }
    
    public void setOtherProductAmeFer(String otherProductAmeFer) {
        this.otherProductAmeFer = otherProductAmeFer;
    }




}


