package org.aepscolombia.platform.models.entity;
// Generated Apr 8, 2014 9:37:27 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AmendmentsFertilizations generated by hbm2java
 */
@Entity
@Table(name="amendments_fertilizations")
public class AmendmentsFertilizations  implements java.io.Serializable {


     private Integer idAmeFer;
     private Fertilizations fertilizations;
     private AmendmentsFertilizers amendmentsFertilizers;
     private String otherProductAmeFer;
     private Double amountProductUsedAmeFer;
     private Boolean status;
     private Integer createdBy;

    public AmendmentsFertilizations() {
    }

	
    public AmendmentsFertilizations(Fertilizations fertilizations) {
        this.fertilizations = fertilizations;
    }
    public AmendmentsFertilizations(Fertilizations fertilizations, AmendmentsFertilizers amendmentsFertilizers, String otherProductAmeFer, Double amountProductUsedAmeFer, Boolean status, Integer createdBy) {
       this.fertilizations = fertilizations;
       this.amendmentsFertilizers = amendmentsFertilizers;
       this.otherProductAmeFer = otherProductAmeFer;
       this.amountProductUsedAmeFer = amountProductUsedAmeFer;
       this.status = status;
       this.createdBy = createdBy;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_ame_fer", unique=true, nullable=false)
    public Integer getIdAmeFer() {
        return this.idAmeFer;
    }
    
    public void setIdAmeFer(Integer idAmeFer) {
        this.idAmeFer = idAmeFer;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_fertilization_ame_fer", nullable=false)
    public Fertilizations getFertilizations() {
        return this.fertilizations;
    }
    
    public void setFertilizations(Fertilizations fertilizations) {
        this.fertilizations = fertilizations;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_product_ame_fer")
    public AmendmentsFertilizers getAmendmentsFertilizers() {
        return this.amendmentsFertilizers;
    }
    
    public void setAmendmentsFertilizers(AmendmentsFertilizers amendmentsFertilizers) {
        this.amendmentsFertilizers = amendmentsFertilizers;
    }
    
    @Column(name="amount_product_used_ame_fer", nullable=false, precision=22, scale=0)
    public Double getAmountProductUsedAmeFer() {
        return this.amountProductUsedAmeFer;
    }
    
    public void setAmountProductUsedAmeFer(Double amountProductUsedAmeFer) {
        this.amountProductUsedAmeFer = amountProductUsedAmeFer;
    }
    
    @Column(name="other_product_ame_fer", length=65535)
    public String getOtherProductAmeFer() {
        return this.otherProductAmeFer;
    }
    
    public void setOtherProductAmeFer(String otherProductAmeFer) {
        this.otherProductAmeFer = otherProductAmeFer;
    }
    
    @Column(name="status")
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    
    @Column(name="created_by")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }




}


