package org.aepscolombia.platform.models.entity;
// Generated Apr 8, 2014 9:37:27 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ExtensionAgents generated by hbm2java
 */
@Entity
@Table(name="association")
public class Association  implements java.io.Serializable {


    private Integer idAsc;
    private Entities entities;
    private Integer status;
    private Integer createdBy;
    private String nameAsc;

    public Association() {
    }
    
    public Association(Integer idAsc) {
        this.idAsc = idAsc;
    }

	
    public Association(Entities entities) {
        this.entities = entities;
    }
    
    public Association(Entities entities, String nameAsc, Integer status, Integer createdBy) {
       this.entities = entities;
       this.status = status;
       this.nameAsc = nameAsc;
       this.createdBy = createdBy;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_asc", unique=true, nullable=false)
    public Integer getIdAsc() {
        return this.idAsc;
    }
    
    public void setIdAsc(Integer idAsc) {
        this.idAsc = idAsc;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_entity_asc", nullable=false)
    public Entities getEntities() {
        return this.entities;
    }
    
    public void setEntities(Entities entities) {
        this.entities = entities;
    }
    
    @Column(name="name_asc", length=200)
    public String getNameAsc() {
        return this.nameAsc;
    }
    
    public void setNameAsc(String nameAsc) {
        this.nameAsc = nameAsc;
    }
    
    @Column(name="status")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    
    @Column(name="created_by")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

}


