package org.aepscolombia.platform.models.entity;
// Generated Apr 8, 2014 9:37:27 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Beans generated by hbm2java
 */
@Entity
@Table(name="beans"
    ,catalog="madr_bd13"
)
public class Beans  implements java.io.Serializable {


     private Integer idBea;
     private ProductionEvents productionEvents;
     private GrowingEnvironment growingEnvironment;
     private SeedsTypes seedsTypes;
     private SeedsInoculations seedsInoculations;
     private Integer seedsNumberSiteBea;
     private String otroInoculationBea;
     private Boolean status;
     private Integer createdBy;

    public Beans() {
    }

	
    public Beans(ProductionEvents productionEvents) {
        this.productionEvents = productionEvents;
    }
    public Beans(ProductionEvents productionEvents, GrowingEnvironment growingEnvironment, SeedsTypes seedsTypes, SeedsInoculations seedsInoculations, Integer seedsNumberSiteBea, String otroInoculationBea, Boolean status, Integer createdBy) {
       this.productionEvents = productionEvents;
       this.growingEnvironment = growingEnvironment;
       this.seedsTypes = seedsTypes;
       this.seedsInoculations = seedsInoculations;
       this.seedsNumberSiteBea = seedsNumberSiteBea;
       this.otroInoculationBea = otroInoculationBea;
       this.status = status;
       this.createdBy = createdBy;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_bea", unique=true, nullable=false)
    public Integer getIdBea() {
        return this.idBea;
    }
    
    public void setIdBea(Integer idBea) {
        this.idBea = idBea;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_production_event_bea", nullable=false)
    public ProductionEvents getProductionEvents() {
        return this.productionEvents;
    }
    
    public void setProductionEvents(ProductionEvents productionEvents) {
        this.productionEvents = productionEvents;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="growing_environment_bea")
    public GrowingEnvironment getGrowingEnvironment() {
        return this.growingEnvironment;
    }
    
    public void setGrowingEnvironment(GrowingEnvironment growingEnvironment) {
        this.growingEnvironment = growingEnvironment;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="seed_type_bea")
    public SeedsTypes getSeedsTypes() {
        return this.seedsTypes;
    }
    
    public void setSeedsTypes(SeedsTypes seedsTypes) {
        this.seedsTypes = seedsTypes;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="seeds_inoculation_bea")
    public SeedsInoculations getSeedsInoculations() {
        return this.seedsInoculations;
    }
    
    public void setSeedsInoculations(SeedsInoculations seedsInoculations) {
        this.seedsInoculations = seedsInoculations;
    }
    
    @Column(name="seeds_number_site_bea")
    public Integer getSeedsNumberSiteBea() {
        return this.seedsNumberSiteBea;
    }
    
    public void setSeedsNumberSiteBea(Integer seedsNumberSiteBea) {
        this.seedsNumberSiteBea = seedsNumberSiteBea;
    }
    
    @Column(name="otro_inoculation_bea", length=65535)
    public String getOtroInoculationBea() {
        return this.otroInoculationBea;
    }
    
    public void setOtroInoculationBea(String otroInoculationBea) {
        this.otroInoculationBea = otroInoculationBea;
    }
    
    @Column(name="status")
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    
    @Column(name="created_by")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }




}


