package org.aepscolombia.platform.models.entity;
// Generated Apr 8, 2014 9:37:27 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ChemicalFertilizations generated by hbm2java
 */
@Entity
@Table(name="chemical_fertilizations"
    ,catalog="madr_bd13"
)
public class ChemicalFertilizations  implements java.io.Serializable {


     private Integer idCheFer;
     private ChemicalFertilizers chemicalFertilizers;
     private Fertilizations fertilizations;
     private String otherProductCheFer;
     private Boolean status;
     private Integer createdBy;

    public ChemicalFertilizations() {
    }

	
    public ChemicalFertilizations(Fertilizations fertilizations) {
        this.fertilizations = fertilizations;
    }
    public ChemicalFertilizations(ChemicalFertilizers chemicalFertilizers, Fertilizations fertilizations, String otherProductCheFer, Boolean status, Integer createdBy) {
       this.chemicalFertilizers = chemicalFertilizers;
       this.fertilizations = fertilizations;
       this.otherProductCheFer = otherProductCheFer;
       this.status = status;
       this.createdBy = createdBy;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_che_fer", unique=true, nullable=false)
    public Integer getIdCheFer() {
        return this.idCheFer;
    }
    
    public void setIdCheFer(Integer idCheFer) {
        this.idCheFer = idCheFer;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_product_che_fer")
    public ChemicalFertilizers getChemicalFertilizers() {
        return this.chemicalFertilizers;
    }
    
    public void setChemicalFertilizers(ChemicalFertilizers chemicalFertilizers) {
        this.chemicalFertilizers = chemicalFertilizers;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_fertilization_che_fer", nullable=false)
    public Fertilizations getFertilizations() {
        return this.fertilizations;
    }
    
    public void setFertilizations(Fertilizations fertilizations) {
        this.fertilizations = fertilizations;
    }
    
    @Column(name="other_product_che_fer", length=65535)
    public String getOtherProductCheFer() {
        return this.otherProductCheFer;
    }
    
    public void setOtherProductCheFer(String otherProductCheFer) {
        this.otherProductCheFer = otherProductCheFer;
    }
    
    @Column(name="status")
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    
    @Column(name="created_by")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }




}


