package org.aepscolombia.platform.models.entity;
// Generated Apr 8, 2014 9:37:27 AM by Hibernate Tools 3.2.1.GA

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChemicalFertilizers generated by hbm2java
 */
@Entity
@Table(name="chemical_fertilizers")
public class ChemicalFertilizers  implements java.io.Serializable {


     private Integer idCheFer;
     private String nameCheFer;
     private Boolean statusCheFer;

    public ChemicalFertilizers() {
    }
    
    public ChemicalFertilizers(Integer idCheFer) {
       this.idCheFer = idCheFer;
    } 
    
    public ChemicalFertilizers(Integer idCheFer, String nameCheFer) {
       this.idCheFer = idCheFer;
       this.nameCheFer = nameCheFer;
    }    

    public ChemicalFertilizers(String nameCheFer, Boolean statusCheFer) {
       this.nameCheFer = nameCheFer;
       this.statusCheFer = statusCheFer;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_che_fer", unique=true, nullable=false)
    public Integer getIdCheFer() {
        return this.idCheFer;
    }
    
    public void setIdCheFer(Integer idCheFer) {
        this.idCheFer = idCheFer;
    }
    
    @Column(name="name_che_fer", length=45)
    public String getNameCheFer() {
        return this.nameCheFer;
    }
    
    public void setNameCheFer(String nameCheFer) {
        this.nameCheFer = nameCheFer;
    }
    
    @Column(name="status_che_fer")
    public Boolean getStatusCheFer() {
        return this.statusCheFer;
    }
    
    public void setStatusCheFer(Boolean statusCheFer) {
        this.statusCheFer = statusCheFer;
    }

}


