package org.aepscolombia.platform.models.entity;
// Generated Apr 8, 2014 9:37:27 AM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ChemicalFertilizers generated by hbm2java
 */
@Entity
@Table(name="chemical_fertilizations_chemical_elements")
public class ChemicalFertilizationsChemicalElements  implements java.io.Serializable {


    private Integer idChemFertChemElem;

    public ChemicalFertilizationsChemicalElements() {
    }
    
    public ChemicalFertilizationsChemicalElements(Integer idChemFertChemElem) {
       this.idChemFertChemElem = idChemFertChemElem;
    }    
   
    @Id @GeneratedValue(strategy=IDENTITY)    
    @Column(name="id_chem_fert_chem_elem", unique=true, nullable=false)
    public Integer getIdChemFertChemElem() {
        return this.idChemFertChemElem;
    }
    
    public void setIdChemFertChemElem(Integer idChemFertChemElem) {
        this.idChemFertChemElem = idChemFertChemElem;
    }

}


