package org.aepscolombia.platform.models.entity;
// Generated Apr 8, 2014 9:37:27 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Communes generated by hbm2java
 */
@Entity
@Table(name="communes"
    , uniqueConstraints = @UniqueConstraint(columnNames="code_com") 
)
public class Communes  implements java.io.Serializable {


     private int idCom;
     private Municipalities municipalities;
     private String codeCom;
     private String nameCom;
     private Boolean status;
     private Integer createdBy;

    public Communes() {
    }

	
    public Communes(int idCom, Municipalities municipalities, String codeCom, String nameCom) {
        this.idCom = idCom;
        this.municipalities = municipalities;
        this.codeCom = codeCom;
        this.nameCom = nameCom;
    }
    public Communes(int idCom, Municipalities municipalities, String codeCom, String nameCom, Boolean status, Integer createdBy) {
       this.idCom = idCom;
       this.municipalities = municipalities;
       this.codeCom = codeCom;
       this.nameCom = nameCom;
       this.status = status;
       this.createdBy = createdBy;
    }
   
     @Id 
    
    @Column(name="id_com", unique=true, nullable=false)
    public int getIdCom() {
        return this.idCom;
    }
    
    public void setIdCom(int idCom) {
        this.idCom = idCom;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_municipality_com", nullable=false)
    public Municipalities getMunicipalities() {
        return this.municipalities;
    }
    
    public void setMunicipalities(Municipalities municipalities) {
        this.municipalities = municipalities;
    }
    
    @Column(name="code_com", unique=true, nullable=false, length=10)
    public String getCodeCom() {
        return this.codeCom;
    }
    
    public void setCodeCom(String codeCom) {
        this.codeCom = codeCom;
    }
    
    @Column(name="name_com", nullable=false, length=100)
    public String getNameCom() {
        return this.nameCom;
    }
    
    public void setNameCom(String nameCom) {
        this.nameCom = nameCom;
    }
    
    @Column(name="status")
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    
    @Column(name="created_by")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }




}


