package org.aepscolombia.platform.models.entity;
// Generated Apr 8, 2014 9:37:27 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Controls generated by hbm2java
 */
@Entity
@Table(name="controls")
public class Controls  implements java.io.Serializable {


     private Integer idCon;
     private Diseases diseases;
     private Weeds weeds;
     private ControlsTypes controlsTypes;
     private ChemicalsControls chemicalsControls;
     private ProductionEvents productionEvents;
     private TargetsTypes targetsTypes;
     private OrganicControls organicControls;
     private DoseUnits doseUnits;
     private Pests pests;
     private Date dateCon;
     private Double dosisCon;
     private String otherPestCon;
     private String otherDiseaseCon;
     private String otroWeedCon;
     private String otherChemicalProductCon;
     private String otherOrganicProductCon;
     private Boolean cleaningsCon;
     private Integer cleaningsFrequenceCon;
     private String commentCon;
     private BigDecimal costInputCon;
     private Integer costFormAppCon;
     private BigDecimal costAppCon;

     private Boolean status;
     private Integer createdBy;
    
    public Controls() {
    }

	
    public Controls(ControlsTypes controlsTypes, ProductionEvents productionEvents) {
        this.controlsTypes = controlsTypes;
        this.productionEvents = productionEvents;
    }
    public Controls(Diseases diseases, Weeds weeds, ControlsTypes controlsTypes, ChemicalsControls chemicalsControls, ProductionEvents productionEvents, TargetsTypes targetsTypes, OrganicControls organicControls, DoseUnits doseUnits, Pests pests, Date dateCon, Double dosisCon, String otherPestCon, String otherDiseaseCon, String otroWeedCon, String otherChemicalProductCon, String otherOrganicProductCon, Boolean cleaningsCon, Integer cleaningsFrequenceCon, String commentCon ,Boolean status, Integer createdBy, BigDecimal costInputCon, Integer costFormAppCon, BigDecimal costAppCon) {
       this.diseases = diseases;
       this.weeds = weeds;
       this.controlsTypes = controlsTypes;
       this.chemicalsControls = chemicalsControls;
       this.productionEvents = productionEvents;
       this.targetsTypes = targetsTypes;
       this.organicControls = organicControls;
       this.doseUnits = doseUnits;
       this.pests = pests;
       this.dateCon = dateCon;
       this.dosisCon = dosisCon;
       this.otherPestCon = otherPestCon;
       this.otherDiseaseCon = otherDiseaseCon;
       this.otroWeedCon = otroWeedCon;
       this.otherChemicalProductCon = otherChemicalProductCon;
       this.otherOrganicProductCon = otherOrganicProductCon;
       this.cleaningsCon = cleaningsCon;
       this.cleaningsFrequenceCon = cleaningsFrequenceCon;
       this.commentCon=commentCon;
       this.status = status;
       this.createdBy = createdBy;
       this.costInputCon   = costInputCon;
       this.costFormAppCon   = costFormAppCon;
       this.costAppCon   =   costAppCon;   
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_con", unique=true, nullable=false)
    public Integer getIdCon() {
        return this.idCon;
    }
    
    public void setIdCon(Integer idCon) {
        this.idCon = idCon;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_disease_con")
    public Diseases getDiseases() {
        return this.diseases;
    }
    
    public void setDiseases(Diseases diseases) {
        this.diseases = diseases;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_weed_con")
    public Weeds getWeeds() {
        return this.weeds;
    }
    
    public void setWeeds(Weeds weeds) {
        this.weeds = weeds;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="control_type_con", nullable=false)
    public ControlsTypes getControlsTypes() {
        return this.controlsTypes;
    }
    
    public void setControlsTypes(ControlsTypes controlsTypes) {
        this.controlsTypes = controlsTypes;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="chemical_product_used_con")
    public ChemicalsControls getChemicalsControls() {
        return this.chemicalsControls;
    }
    
    public void setChemicalsControls(ChemicalsControls chemicalsControls) {
        this.chemicalsControls = chemicalsControls;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_production_event_con", nullable=false)
    public ProductionEvents getProductionEvents() {
        return this.productionEvents;
    }
    
    public void setProductionEvents(ProductionEvents productionEvents) {
        this.productionEvents = productionEvents;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="target_type_con")
    public TargetsTypes getTargetsTypes() {
        return this.targetsTypes;
    }
    
    public void setTargetsTypes(TargetsTypes targetsTypes) {
        this.targetsTypes = targetsTypes;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="organic_product_used_con")
    public OrganicControls getOrganicControls() {
        return this.organicControls;
    }
    
    public void setOrganicControls(OrganicControls organicControls) {
        this.organicControls = organicControls;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dose_units_con")
    public DoseUnits getDoseUnits() {
        return this.doseUnits;
    }
    
    public void setDoseUnits(DoseUnits doseUnits) {
        this.doseUnits = doseUnits;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pest_con")
    public Pests getPests() {
        return this.pests;
    }
    
    public void setPests(Pests pests) {
        this.pests = pests;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_con", length=19)
    public Date getDateCon() {
        return this.dateCon;
    }
    
    public void setDateCon(Date dateCon) {
        this.dateCon = dateCon;
    }
    
    @Column(name="dosis_con", precision=22, scale=0)
    public Double getDosisCon() {
        return this.dosisCon;
    }
    
    public void setDosisCon(Double dosisCon) {
        this.dosisCon = dosisCon;
    }
    
    @Column(name="other_pest_con", length=65535)
    public String getOtherPestCon() {
        return this.otherPestCon;
    }
    
    public void setOtherPestCon(String otherPestCon) {
        this.otherPestCon = otherPestCon;
    }
    
    @Column(name="other_disease_con", length=65535)
    public String getOtherDiseaseCon() {
        return this.otherDiseaseCon;
    }
    
    public void setOtherDiseaseCon(String otherDiseaseCon) {
        this.otherDiseaseCon = otherDiseaseCon;
    }
    
    @Column(name="otro_weed_con", length=65535)
    public String getOtroWeedCon() {
        return this.otroWeedCon;
    }
    
    public void setOtroWeedCon(String otroWeedCon) {
        this.otroWeedCon = otroWeedCon;
    }
    
    @Column(name="other_chemical_product_con", length=65535)
    public String getOtherChemicalProductCon() {
        return this.otherChemicalProductCon;
    }
    
    public void setOtherChemicalProductCon(String otherChemicalProductCon) {
        this.otherChemicalProductCon = otherChemicalProductCon;
    }
    
    @Column(name="other_organic_product_con", length=65535)
    public String getOtherOrganicProductCon() {
        return this.otherOrganicProductCon;
    }
    
    public void setOtherOrganicProductCon(String otherOrganicProductCon) {
        this.otherOrganicProductCon = otherOrganicProductCon;
    }
    
    @Column(name="cleanings_con")
    public Boolean getCleaningsCon() {
        return this.cleaningsCon;
    }
    
    public void setCleaningsCon(Boolean cleaningsCon) {
        this.cleaningsCon = cleaningsCon;
    }
    
    @Column(name="cleanings_frequence_con")
    public Integer getCleaningsFrequenceCon() {
        return this.cleaningsFrequenceCon;
    }
    
    public void setCleaningsFrequenceCon(Integer cleaningsFrequenceCon) {
        this.cleaningsFrequenceCon = cleaningsFrequenceCon;
    }    
    
      
    @Column(name="cost_input_con")
    public BigDecimal getCostInputCon() {
        return this.costInputCon;
    }
    
    public void setCostInputCon(BigDecimal costInputCon) {
        this.costInputCon = costInputCon;
    }
    
    @Column(name="cost_form_app_con")
    public Integer getCostFormAppCon() {
        return this.costFormAppCon;
    }
    
    public void setCostFormAppCon(Integer costFormAppCon) {
        this.costFormAppCon = costFormAppCon;
    }
     
    @Column(name="cost_app_con")
    public BigDecimal getCostAppCon() {
        return this.costAppCon;
    }
    
    public void setCostAppCon(BigDecimal costAppCon) {
        this.costAppCon = costAppCon;
    }
    
      
    @Column(name="comment_con")
    public String getCommentCon() {
        return this.commentCon;
    }
    
    public void setCommentCon(String commentCon) {
        this.commentCon = commentCon;
    }
    
    
    @Column(name="status")
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    
    @Column(name="created_by")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }




}


