package org.aepscolombia.platform.models.entity;
// Generated Jan 21, 2014 11:35:29 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entities generated by hbm2java
 */
@Entity
@Table(name="entities"
    ,catalog="madr_bd10"
)
public class Entities  implements java.io.Serializable {


     private Integer idEnt;
     private Municipalities municipalities;
     private DocumentsTypes documentsTypes;
     private EntitiesTypes entitiesTypes;
     private Integer idProjectEnt;
     private String documentNumberEnt;
     private String documentIssuePlaceEnt;
     private String nameEnt;
     private Boolean inAssociationEnt;
     private String emailEnt;
     private String email2Ent;
     private String addressEnt;
     private Integer cellphone2Ent;
     private Integer phoneEnt;
     private Long cellphoneEnt;
     private boolean statusEnt;
     private String genderEnt;
     private String civilStatusEnt;
     private Integer validationNumberEnt;
     private String educationLevelEnt;
     private Date dateOfBirthEnt;
     private String firstName1Ent;
     private String firstName2Ent;
     private String lastName1Ent;
     private String lastName2Ent;

    public Entities() {
    }

	
    public Entities(Municipalities municipalities, DocumentsTypes documentsTypes, EntitiesTypes entitiesTypes, String documentNumberEnt, String nameEnt, String emailEnt, String addressEnt, boolean statusEnt) {
        this.municipalities = municipalities;
        this.documentsTypes = documentsTypes;
        this.entitiesTypes = entitiesTypes;
        this.documentNumberEnt = documentNumberEnt;
        this.nameEnt = nameEnt;
        this.emailEnt = emailEnt;
        this.addressEnt = addressEnt;
        this.statusEnt = statusEnt;
    }
    public Entities(Municipalities municipalities, DocumentsTypes documentsTypes, EntitiesTypes entitiesTypes, Integer idProjectEnt, String documentNumberEnt, String documentIssuePlaceEnt, String nameEnt, Boolean inAssociationEnt, String emailEnt, String email2Ent, String addressEnt, Integer cellphone2Ent, Integer phoneEnt, Long cellphoneEnt, boolean statusEnt, String genderEnt, String civilStatusEnt, Integer validationNumberEnt, String educationLevelEnt, Date dateOfBirthEnt, String firstName1Ent, String firstName2Ent, String lastName1Ent, String lastName2Ent) {
       this.municipalities = municipalities;
       this.documentsTypes = documentsTypes;
       this.entitiesTypes = entitiesTypes;
       this.idProjectEnt = idProjectEnt;
       this.documentNumberEnt = documentNumberEnt;
       this.documentIssuePlaceEnt = documentIssuePlaceEnt;
       this.nameEnt = nameEnt;
       this.inAssociationEnt = inAssociationEnt;
       this.emailEnt = emailEnt;
       this.email2Ent = email2Ent;
       this.addressEnt = addressEnt;
       this.cellphone2Ent = cellphone2Ent;
       this.phoneEnt = phoneEnt;
       this.cellphoneEnt = cellphoneEnt;
       this.statusEnt = statusEnt;
       this.genderEnt = genderEnt;
       this.civilStatusEnt = civilStatusEnt;
       this.validationNumberEnt = validationNumberEnt;
       this.educationLevelEnt = educationLevelEnt;
       this.dateOfBirthEnt = dateOfBirthEnt;
       this.firstName1Ent = firstName1Ent;
       this.firstName2Ent = firstName2Ent;
       this.lastName1Ent = lastName1Ent;
       this.lastName2Ent = lastName2Ent;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_ent", unique=true, nullable=false)
    public Integer getIdEnt() {
        return this.idEnt;
    }
    
    public void setIdEnt(Integer idEnt) {
        this.idEnt = idEnt;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_municipality_ent", nullable=true)
    public Municipalities getMunicipalities() {
        return this.municipalities;
    }
    
    public void setMunicipalities(Municipalities municipalities) {
        this.municipalities = municipalities;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="document_type_ent", nullable=true)
    public DocumentsTypes getDocumentsTypes() {
        return this.documentsTypes;
    }
    
    public void setDocumentsTypes(DocumentsTypes documentsTypes) {
        this.documentsTypes = documentsTypes;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="entity_type_ent", nullable=false)
    public EntitiesTypes getEntitiesTypes() {
        return this.entitiesTypes;
    }
    
    public void setEntitiesTypes(EntitiesTypes entitiesTypes) {
        this.entitiesTypes = entitiesTypes;
    }
    
    @Column(name="id_project_ent")
    public Integer getIdProjectEnt() {
        return this.idProjectEnt;
    }
    
    public void setIdProjectEnt(Integer idProjectEnt) {
        this.idProjectEnt = idProjectEnt;
    }
    
    @Column(name="document_number_ent", nullable=true, length=20)
    public String getDocumentNumberEnt() {
        return this.documentNumberEnt;
    }
    
    public void setDocumentNumberEnt(String documentNumberEnt) {
        this.documentNumberEnt = documentNumberEnt;
    }
    
    @Column(name="document_issue_place_ent", length=70)
    public String getDocumentIssuePlaceEnt() {
        return this.documentIssuePlaceEnt;
    }
    
    public void setDocumentIssuePlaceEnt(String documentIssuePlaceEnt) {
        this.documentIssuePlaceEnt = documentIssuePlaceEnt;
    }
    
    @Column(name="name_ent", nullable=true, length=100)
    public String getNameEnt() {
        return this.nameEnt;
    }
    
    public void setNameEnt(String nameEnt) {
        this.nameEnt = nameEnt;
    }
    
    @Column(name="in_association_ent")
    public Boolean getInAssociationEnt() {
        return this.inAssociationEnt;
    }
    
    public void setInAssociationEnt(Boolean inAssociationEnt) {
        this.inAssociationEnt = inAssociationEnt;
    }
    
    @Column(name="email_ent", nullable=false, length=45)
    public String getEmailEnt() {
        return this.emailEnt;
    }
    
    public void setEmailEnt(String emailEnt) {
        this.emailEnt = emailEnt;
    }
    
    @Column(name="email_2_ent", length=45)
    public String getEmail2Ent() {
        return this.email2Ent;
    }
    
    public void setEmail2Ent(String email2Ent) {
        this.email2Ent = email2Ent;
    }
    
    @Column(name="address_ent", nullable=true, length=200)
    public String getAddressEnt() {
        return this.addressEnt;
    }
    
    public void setAddressEnt(String addressEnt) {
        this.addressEnt = addressEnt;
    }
    
    @Column(name="cellphone2_ent")
    public Integer getCellphone2Ent() {
        return this.cellphone2Ent;
    }
    
    public void setCellphone2Ent(Integer cellphone2Ent) {
        this.cellphone2Ent = cellphone2Ent;
    }
    
    @Column(name="phone_ent")
    public Integer getPhoneEnt() {
        return this.phoneEnt;
    }
    
    public void setPhoneEnt(Integer phoneEnt) {
        this.phoneEnt = phoneEnt;
    }
    
    @Column(name="cellphone_ent")
    public Long getCellphoneEnt() {
        return this.cellphoneEnt;
    }
    
    public void setCellphoneEnt(Long cellphoneEnt) {
        this.cellphoneEnt = cellphoneEnt;
    }
    
    @Column(name="status_ent", nullable=false)
    public boolean isStatusEnt() {
        return this.statusEnt;
    }
    
    public void setStatusEnt(boolean statusEnt) {
        this.statusEnt = statusEnt;
    }
    
    @Column(name="gender_ent", length=10)
    public String getGenderEnt() {
        return this.genderEnt;
    }
    
    public void setGenderEnt(String genderEnt) {
        this.genderEnt = genderEnt;
    }
    
    @Column(name="civil_status_ent", length=11)
    public String getCivilStatusEnt() {
        return this.civilStatusEnt;
    }
    
    public void setCivilStatusEnt(String civilStatusEnt) {
        this.civilStatusEnt = civilStatusEnt;
    }
    
    @Column(name="validation_number_ent")
    public Integer getValidationNumberEnt() {
        return this.validationNumberEnt;
    }
    
    public void setValidationNumberEnt(Integer validationNumberEnt) {
        this.validationNumberEnt = validationNumberEnt;
    }
    
    @Column(name="education_level_ent", length=13)
    public String getEducationLevelEnt() {
        return this.educationLevelEnt;
    }
    
    public void setEducationLevelEnt(String educationLevelEnt) {
        this.educationLevelEnt = educationLevelEnt;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_of_birth_ent", length=19)
    public Date getDateOfBirthEnt() {
        return this.dateOfBirthEnt;
    }
    
    public void setDateOfBirthEnt(Date dateOfBirthEnt) {
        this.dateOfBirthEnt = dateOfBirthEnt;
    }
    
    @Column(name="first_name_1_ent", length=50)
    public String getFirstName1Ent() {
        return this.firstName1Ent;
    }
    
    public void setFirstName1Ent(String firstName1Ent) {
        this.firstName1Ent = firstName1Ent;
    }
    
    @Column(name="first_name_2_ent", length=50)
    public String getFirstName2Ent() {
        return this.firstName2Ent;
    }
    
    public void setFirstName2Ent(String firstName2Ent) {
        this.firstName2Ent = firstName2Ent;
    }
    
    @Column(name="last_name_1_ent", length=50)
    public String getLastName1Ent() {
        return this.lastName1Ent;
    }
    
    public void setLastName1Ent(String lastName1Ent) {
        this.lastName1Ent = lastName1Ent;
    }
    
    @Column(name="last_name_2_ent", length=50)
    public String getLastName2Ent() {
        return this.lastName2Ent;
    }
    
    public void setLastName2Ent(String lastName2Ent) {
        this.lastName2Ent = lastName2Ent;
    }

}


