package org.aepscolombia.platform.models.entity;
// Generated Jan 21, 2014 11:35:29 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Farms generated by hbm2java
 */
@Entity
@Table(name="farms"
    ,catalog="madr_bd11"
)
public class Farms  implements java.io.Serializable {


     private Integer idFar;
     private MeasureUnits measureUnits;
     private Municipalities municipalities;
     private Distircts distircts;
     private String nameFar;
     private String addressFar;
     private Integer phoneFar;
     private boolean georefFar;
     private Double latitudeFar;
     private Double longitudeFar;
     private Double altitudeFar;
     private Double areaFar;
     private String idProjectFar;
     private String nameCommuneFar;
     private boolean statusFar;

    public Farms() {
    }

    public Farms(Integer idFar) {
        this.idFar = idFar;
    }
	
    public Farms(Municipalities municipalities, String nameFar, String addressFar, boolean georefFar, boolean statusFar) {
        this.municipalities = municipalities;
        this.nameFar = nameFar;
        this.addressFar = addressFar;
        this.georefFar = georefFar;
        this.statusFar = statusFar;
    }
    public Farms(MeasureUnits measureUnits, Municipalities municipalities, Distircts distircts, String nameFar, String addressFar, Integer phoneFar, boolean georefFar, Double latitudeFar, Double longitudeFar, Double altitudeFar, Double areaFar, String idProjectFar, String nameCommuneFar) {
       this.measureUnits = measureUnits;
       this.municipalities = municipalities;
       this.distircts = distircts;
       this.nameFar = nameFar;
       this.addressFar = addressFar;
       this.phoneFar = phoneFar;
       this.georefFar = georefFar;
       this.latitudeFar = latitudeFar;
       this.longitudeFar = longitudeFar;
       this.altitudeFar = altitudeFar;
       this.areaFar = areaFar;
       this.idProjectFar = idProjectFar;
       this.nameCommuneFar = nameCommuneFar;
       this.statusFar = statusFar;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_far", unique=true, nullable=false)
    public Integer getIdFar() {
        return this.idFar;
    }
    
    public void setIdFar(Integer idFar) {
        this.idFar = idFar;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="unit_area_far")
    public MeasureUnits getMeasureUnits() {
        return this.measureUnits;
    }
    
    public void setMeasureUnits(MeasureUnits measureUnits) {
        this.measureUnits = measureUnits;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_municipipality_far", nullable=false)
    public Municipalities getMunicipalities() {
        return this.municipalities;
    }
    
    public void setMunicipalities(Municipalities municipalities) {
        this.municipalities = municipalities;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_district_far")
    public Distircts getDistircts() {
        return this.distircts;
    }
    
    public void setDistircts(Distircts distircts) {
        this.distircts = distircts;
    }
    
    @Column(name="name_far", nullable=false, length=45)
    public String getNameFar() {
        return this.nameFar;
    }
    
    public void setNameFar(String nameFar) {
        this.nameFar = nameFar;
    }
    
    @Column(name="address_far", nullable=false, length=45)
    public String getAddressFar() {
        return this.addressFar;
    }
    
    public void setAddressFar(String addressFar) {
        this.addressFar = addressFar;
    }
    
    @Column(name="phone_far")
    public Integer getPhoneFar() {
        return this.phoneFar;
    }
    
    public void setPhoneFar(Integer phoneFar) {
        this.phoneFar = phoneFar;
    }
    
    @Column(name="georef_far", nullable=false)
    public boolean isGeorefFar() {
        return this.georefFar;
    }
    
    public void setGeorefFar(boolean georefFar) {
        this.georefFar = georefFar;
    }
    
    @Column(name="latitude_far", precision=22, scale=0)
    public Double getLatitudeFar() {
        return this.latitudeFar;
    }
    
    public void setLatitudeFar(Double latitudeFar) {
        this.latitudeFar = latitudeFar;
    }
    
    @Column(name="longitude_far", precision=22, scale=0)
    public Double getLongitudeFar() {
        return this.longitudeFar;
    }
    
    public void setLongitudeFar(Double longitudeFar) {
        this.longitudeFar = longitudeFar;
    }
    
    @Column(name="altitude_far", precision=22, scale=0)
    public Double getAltitudeFar() {
        return this.altitudeFar;
    }
    
    public void setAltitudeFar(Double altitudeFar) {
        this.altitudeFar = altitudeFar;
    }
    
    @Column(name="area_far", precision=22, scale=0)
    public Double getAreaFar() {
        return this.areaFar;
    }
    
    public void setAreaFar(Double areaFar) {
        this.areaFar = areaFar;
    }
    
    @Column(name="id_project_far", length=4)
    public String getIdProjectFar() {
        return this.idProjectFar;
    }
    
    public void setIdProjectFar(String idProjectFar) {
        this.idProjectFar = idProjectFar;
    }
    
    @Column(name="name_commune_far", length=100)
    public String getNameCommuneFar() {
        return this.nameCommuneFar;
    }
    
    public void setNameCommuneFar(String nameCommuneFar) {
        this.nameCommuneFar = nameCommuneFar;
    }
    
    @Column(name="status_far", nullable=false)
    public boolean isStatusFar() {
        return this.statusFar;
    }
    
    public void setStatusFar(boolean statusFar) {
        this.statusFar = statusFar;
    }

}


