package org.aepscolombia.platform.models.entity;
// Generated Apr 8, 2014 9:37:27 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FarmsProducersId generated by hbm2java
 */
@Embeddable
public class FarmsProducersId  implements java.io.Serializable {


     private int idFarmFarPro;
     private int idProducerFarPro;

    public FarmsProducersId() {
    }

    public FarmsProducersId(int idFarmFarPro, int idProducerFarPro) {
       this.idFarmFarPro = idFarmFarPro;
       this.idProducerFarPro = idProducerFarPro;
    }
   

    @Column(name="id_farm_far_pro", nullable=false)
    public int getIdFarmFarPro() {
        return this.idFarmFarPro;
    }
    
    public void setIdFarmFarPro(int idFarmFarPro) {
        this.idFarmFarPro = idFarmFarPro;
    }

    @Column(name="id_producer_far_pro", nullable=false)
    public int getIdProducerFarPro() {
        return this.idProducerFarPro;
    }
    
    public void setIdProducerFarPro(int idProducerFarPro) {
        this.idProducerFarPro = idProducerFarPro;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FarmsProducersId) ) return false;
		 FarmsProducersId castOther = ( FarmsProducersId ) other; 
         
		 return (this.getIdFarmFarPro()==castOther.getIdFarmFarPro())
 && (this.getIdProducerFarPro()==castOther.getIdProducerFarPro());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdFarmFarPro();
         result = 37 * result + this.getIdProducerFarPro();
         return result;
   }   


}


