package org.aepscolombia.platform.models.entity;
// Generated Apr 8, 2014 9:37:27 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FarmsProducers generated by hbm2java
 */
@Entity
@Table(name="farms_producers"
    ,catalog="madr_bd13"
)
public class FarmsProducers  implements java.io.Serializable {


     private FarmsProducersId id;
     private Producers producers;
     private Farms farms;
     private Integer createdBy;

    public FarmsProducers() {
    }

	
    public FarmsProducers(FarmsProducersId id, Producers producers, Farms farms) {
        this.id = id;
        this.producers = producers;
        this.farms = farms;
    }
    public FarmsProducers(FarmsProducersId id, Producers producers, Farms farms, Integer createdBy) {
       this.id = id;
       this.producers = producers;
       this.farms = farms;
       this.createdBy = createdBy;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idFarmFarPro", column=@Column(name="id_farm_far_pro", nullable=false) ), 
        @AttributeOverride(name="idProducerFarPro", column=@Column(name="id_producer_far_pro", nullable=false) ) } )
    public FarmsProducersId getId() {
        return this.id;
    }
    
    public void setId(FarmsProducersId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_producer_far_pro", nullable=false, insertable=false, updatable=false)
    public Producers getProducers() {
        return this.producers;
    }
    
    public void setProducers(Producers producers) {
        this.producers = producers;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_farm_far_pro", nullable=false, insertable=false, updatable=false)
    public Farms getFarms() {
        return this.farms;
    }
    
    public void setFarms(Farms farms) {
        this.farms = farms;
    }
    
    @Column(name="created_by")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }




}


