package org.aepscolombia.platform.models.entity;
// Generated Apr 8, 2014 9:37:27 AM by Hibernate Tools 3.2.1.GA

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FertilizationsTypes generated by hbm2java
 */
@Entity
@Table(name="fertilizations_types")
public class FertilizationsTypes  implements java.io.Serializable {


     private Integer idFerTyp;
     private String nameFerTyp;
     private IdiomCountry countryFerTyp;

    public FertilizationsTypes() {
    }

	
    public FertilizationsTypes(String nameFerTyp) {
        this.nameFerTyp = nameFerTyp;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_fer_typ", unique=true, nullable=false)
    public Integer getIdFerTyp() {
        return this.idFerTyp;
    }
    
    public void setIdFerTyp(Integer idFerTyp) {
        this.idFerTyp = idFerTyp;
    }
    
    @Column(name="name_fer_typ", nullable=false, length=45)
    public String getNameFerTyp() {
        return this.nameFerTyp;
    }
    
    public void setNameFerTyp(String nameFerTyp) {
        this.nameFerTyp = nameFerTyp;
    }
    
    @ManyToOne
    @JoinColumn(name="country_fer_typ")
    public IdiomCountry getCountryFerTyp() {
        return this.countryFerTyp;
    }
    
    public void setCountryFerTyp(IdiomCountry countryFerTyp) {
        this.countryFerTyp = countryFerTyp;
    }

}


