package org.aepscolombia.platform.models.entity;
// Generated Jan 21, 2014 11:35:29 AM by Hibernate Tools 3.2.1.GA

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FieldTypes generated by hbm2java
 */
@Entity
@Table(name="field_types"
    ,catalog="madr_bd10"
)
public class FieldTypes  implements java.io.Serializable {


     private Integer idFieTyp;
     private String nameFieTyp;
     private boolean statusFieTyp;

    public FieldTypes() {
    }
    
    public FieldTypes(Integer idFieTyp) {
        this.idFieTyp = idFieTyp;
    }
	
    public FieldTypes(String nameFieTyp, boolean statusFieTyp) {
        this.nameFieTyp = nameFieTyp;
        this.statusFieTyp = statusFieTyp;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_fie_typ", unique=true, nullable=false)
    public Integer getIdFieTyp() {
        return this.idFieTyp;
    }
    
    public void setIdFieTyp(Integer idFieTyp) {
        this.idFieTyp = idFieTyp;
    }
    
    @Column(name="name_fie_typ", nullable=false, length=45)
    public String getNameFieTyp() {
        return this.nameFieTyp;
    }
    
    public void setNameFieTyp(String nameFieTyp) {
        this.nameFieTyp = nameFieTyp;
    }
    
    @Column(name="status_fie_typ", nullable=false)
    public boolean isStatusFieTyp() {
        return this.statusFieTyp;
    }
    
    public void setStatusFieTyp(boolean statusFieTyp) {
        this.statusFieTyp = statusFieTyp;
    }

}


