package org.aepscolombia.platform.models.entity;
// Generated Jan 21, 2014 11:35:29 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Flowering generated by hbm2java
 */
@Entity
@Table(name="flowering"
    ,catalog="madr_bd11"
    , uniqueConstraints = @UniqueConstraint(columnNames="id_production_event_flo") 
)
public class Flowering  implements java.io.Serializable {


     private Integer idFlo;
     private ProductionEvents productionEvents;
     private String monthsFlo;

    public Flowering() {
    }

    public Flowering(ProductionEvents productionEvents, String monthsFlo) {
       this.productionEvents = productionEvents;
       this.monthsFlo = monthsFlo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_flo", unique=true, nullable=false)
    public Integer getIdFlo() {
        return this.idFlo;
    }
    
    public void setIdFlo(Integer idFlo) {
        this.idFlo = idFlo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_production_event_flo", unique=true, nullable=false)
    public ProductionEvents getProductionEvents() {
        return this.productionEvents;
    }
    
    public void setProductionEvents(ProductionEvents productionEvents) {
        this.productionEvents = productionEvents;
    }
    
    @Column(name="months_flo", nullable=false, length=9)
    public String getMonthsFlo() {
        return this.monthsFlo;
    }
    
    public void setMonthsFlo(String monthsFlo) {
        this.monthsFlo = monthsFlo;
    }




}


