package org.aepscolombia.platform.models.entity;
// Generated Apr 8, 2014 9:37:27 AM by Hibernate Tools 3.2.1.GA

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PersonType generated by hbm2java
 */
@Entity
@Table(name="genre")
public class Genre  implements java.io.Serializable {


     private Integer idGen;
     private String typeGen;
     private Boolean statusGen;

    public Genre() {
    }

	
    public Genre(String typeGen) {
        this.typeGen = typeGen;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_gen", unique=true, nullable=false)
    public Integer getIdGen() {
        return this.idGen;
    }
    
    public void setIdGen(Integer idGen) {
        this.idGen = idGen;
    }
    
    @Column(name="type_gen", length=45)
    public String getTypeGen() {
        return this.typeGen;
    }
    
    public void setTypeGen(String typeGen) {
        this.typeGen = typeGen;
    }
    
    @Column(name="status_gen")
    public Boolean getStatusGen() {
        return this.statusGen;
    }
    
    public void setStatusGen(Boolean statusGen) {
        this.statusGen = statusGen;
    }

}


