package org.aepscolombia.platform.models.entity;
// Generated Apr 8, 2014 9:37:27 AM by Hibernate Tools 3.2.1.GA

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GrowingEnvironment generated by hbm2java
 */
@Entity
@Table(name="growing_environment")
public class GrowingEnvironment  implements java.io.Serializable {


     private Integer idGroEnv;
     private String nameGroEnv;

    public GrowingEnvironment() {
    }

	
    public GrowingEnvironment(Integer idGroEnv, String nameGroEnv) {
        this.idGroEnv = idGroEnv;
        this.nameGroEnv = nameGroEnv;
    }
   
     @Id 
    
    @Column(name="id_gro_env", unique=true, nullable=false)
    public Integer getIdGroEnv() {
        return this.idGroEnv;
    }
    
    public void setIdGroEnv(Integer idGroEnv) {
        this.idGroEnv = idGroEnv;
    }
    
    @Column(name="name_gro_env", nullable=false, length=45)
    public String getNameGroEnv() {
        return this.nameGroEnv;
    }
    
    public void setNameGroEnv(String nameGroEnv) {
        this.nameGroEnv = nameGroEnv;
    }
    
}


