package org.aepscolombia.platform.models.entity;
// Generated Apr 8, 2014 9:37:27 AM by Hibernate Tools 3.2.1.GA

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * IdiomCountry generated by hbm2java
 */
@Entity
@Table(name="idiom_country")
public class IdiomCountry  implements java.io.Serializable {


     private String acronymIdCo;
     private String countryIdCo;
     private Boolean statusIdCo;

    public IdiomCountry() {
    }

    public IdiomCountry(String acronymIdCo) {
        this.acronymIdCo = acronymIdCo;
    }
	
    public IdiomCountry(String acronymIdCo, String countryIdCo) {
        this.acronymIdCo = acronymIdCo;
        this.countryIdCo = countryIdCo;
    }
   
     @Id 
    
    @Column(name="acronym_id_co", unique=true, nullable=false, length=2)
    public String getAcronymIdCo() {
        return this.acronymIdCo;
    }
    
    public void setAcronymIdCo(String acronymIdCo) {
        this.acronymIdCo = acronymIdCo;
    }
    
    @Column(name="country_id_co", length=50)
    public String getCountryIdCo() {
        return this.countryIdCo;
    }
    
    public void setCountryIdCo(String countryIdCo) {
        this.countryIdCo = countryIdCo;
    }
    
    @Column(name="status_id_co")
    public Boolean getStatusIdCo() {
        return this.statusIdCo;
    }
    
    public void setStatusIdCo(Boolean statusIdCo) {
        this.statusIdCo = statusIdCo;
    }

}


