package org.aepscolombia.platform.models.entity;
// Generated Apr 8, 2014 9:37:27 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Maize generated by hbm2java
 */
@Entity
@Table(name="maize")
public class Maize  implements java.io.Serializable {


     private Integer idMai;
     private SeedsColors seedsColors;
     private ProductionEvents productionEvents;
     private Boolean status;
     private Integer createdBy;
     private Integer seedsNumberSiteMai;

    public Maize() {
    }

	
    public Maize(ProductionEvents productionEvents) {
        this.productionEvents = productionEvents;
    }
    public Maize(SeedsColors seedsColors, ProductionEvents productionEvents, Integer seedsNumberSiteMai, Boolean status, Integer createdBy) {
       this.seedsColors = seedsColors;
       this.seedsNumberSiteMai = seedsNumberSiteMai;
       this.productionEvents = productionEvents;
       this.status = status;
       this.createdBy = createdBy;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_mai", unique=true, nullable=false)
    public Integer getIdMai() {
        return this.idMai;
    }
    
    public void setIdMai(Integer idMai) {
        this.idMai = idMai;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="grain_color_mai")
    public SeedsColors getSeedsColors() {
        return this.seedsColors;
    }
    
    public void setSeedsColors(SeedsColors seedsColors) {
        this.seedsColors = seedsColors;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_production_event_mai", nullable=false)
    public ProductionEvents getProductionEvents() {
        return this.productionEvents;
    }
    
    public void setProductionEvents(ProductionEvents productionEvents) {
        this.productionEvents = productionEvents;
    }
    
    @Column(name="status")
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    
    @Column(name="seeds_number_site_mai")
    public Integer getSeedsNumberSiteMai() {
        return this.seedsNumberSiteMai;
    }
    
    public void setSeedsNumberSiteMai(Integer seedsNumberSiteMai) {
        this.seedsNumberSiteMai = seedsNumberSiteMai;
    }
    
    @Column(name="created_by")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }




}


