package org.aepscolombia.platform.models.entity;
// Generated Apr 8, 2014 9:37:27 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OrganicFertilizers generated by hbm2java
 */
@Entity
@Table(name="organic_fertilizers"
    ,catalog="madr_bd13"
)
public class OrganicFertilizers  implements java.io.Serializable {


     private Integer idOrgFer;
     private String nameOrgFer;
     private Boolean statusOrgFer;

    public OrganicFertilizers() {
    }

    public OrganicFertilizers(String nameOrgFer, Boolean statusOrgFer) {
       this.nameOrgFer = nameOrgFer;
       this.statusOrgFer = statusOrgFer;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_org_fer", unique=true, nullable=false)
    public Integer getIdOrgFer() {
        return this.idOrgFer;
    }
    
    public void setIdOrgFer(Integer idOrgFer) {
        this.idOrgFer = idOrgFer;
    }
    
    @Column(name="name_org_fer", length=45)
    public String getNameOrgFer() {
        return this.nameOrgFer;
    }
    
    public void setNameOrgFer(String nameOrgFer) {
        this.nameOrgFer = nameOrgFer;
    }
    
    @Column(name="status_org_fer")
    public Boolean getStatusOrgFer() {
        return this.statusOrgFer;
    }
    
    public void setStatusOrgFer(Boolean statusOrgFer) {
        this.statusOrgFer = statusOrgFer;
    }

}


