package org.aepscolombia.platform.models.entity;
// Generated Apr 8, 2014 9:37:27 AM by Hibernate Tools 3.2.1.GA

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PersonType generated by hbm2java
 */
@Entity
@Table(name="person_type")
public class PersonType  implements java.io.Serializable {


     private Integer idPerTyp;
     private String namePerTyp;

    public PersonType() {
    }

	
    public PersonType(String namePerTyp) {
        this.namePerTyp = namePerTyp;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_per_typ", unique=true, nullable=false)
    public Integer getIdPerTyp() {
        return this.idPerTyp;
    }
    
    public void setIdPerTyp(Integer idPerTyp) {
        this.idPerTyp = idPerTyp;
    }
    
    @Column(name="name_per_typ", nullable=false, length=45)
    public String getNamePerTyp() {
        return this.namePerTyp;
    }
    
    public void setNamePerTyp(String namePerTyp) {
        this.namePerTyp = namePerTyp;
    }

}


