package org.aepscolombia.platform.models.entity;
// Generated Jan 21, 2014 11:35:29 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PreparationsTypes generated by hbm2java
 */
@Entity
@Table(name="preparations_types"
    ,catalog="madr_bd10"
)
public class PreparationsTypes  implements java.io.Serializable {


     private Integer idPreTyp;
     private String namePreTyp;
     private boolean statusPreTyp;

    public PreparationsTypes() {
    }

	
    public PreparationsTypes(String namePreTyp, boolean statusPreTyp) {
        this.namePreTyp = namePreTyp;
        this.statusPreTyp = statusPreTyp;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_pre_typ", unique=true, nullable=false)
    public Integer getIdPreTyp() {
        return this.idPreTyp;
    }
    
    public void setIdPreTyp(Integer idPreTyp) {
        this.idPreTyp = idPreTyp;
    }
    
    @Column(name="name_pre_typ", nullable=false, length=45)
    public String getNamePreTyp() {
        return this.namePreTyp;
    }
    
    public void setNamePreTyp(String namePreTyp) {
        this.namePreTyp = namePreTyp;
    }
    
    @Column(name="status_pre_typ", nullable=false)
    public boolean isStatusPreTyp() {
        return this.statusPreTyp;
    }
    
    public void setStatusPreTyp(boolean statusPreTyp) {
        this.statusPreTyp = statusPreTyp;
    }

}


