package org.aepscolombia.platform.models.entity;
// Generated Jan 21, 2014 11:35:29 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Privileges generated by hbm2java
 */
@Entity
@Table(name="privileges"
    ,catalog="madr_bd11"
)
public class Privileges  implements java.io.Serializable {


     private Integer idPri;
     private String routePri;
     private String namePri;
     private String descriptionPri;

    public Privileges() {
    }

	
    public Privileges(String routePri, String namePri, String descriptionPri) {
        this.routePri = routePri;
        this.namePri = namePri;
        this.descriptionPri = descriptionPri;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_pri", unique=true, nullable=false)
    public Integer getIdPri() {
        return this.idPri;
    }
    
    public void setIdPri(Integer idPri) {
        this.idPri = idPri;
    }
    
    @Column(name="route_pri", nullable=false, length=250)
    public String getRoutePri() {
        return this.routePri;
    }
    
    public void setRoutePri(String routePri) {
        this.routePri = routePri;
    }
    
    @Column(name="name_pri", nullable=false, length=50)
    public String getNamePri() {
        return this.namePri;
    }
    
    public void setNamePri(String namePri) {
        this.namePri = namePri;
    }
    
    @Column(name="description_pri", nullable=false, length=250)
    public String getDescriptionPri() {
        return this.descriptionPri;
    }
    
    public void setDescriptionPri(String descriptionPri) {
        this.descriptionPri = descriptionPri;
    }

}


