package org.aepscolombia.platform.models.entity;
// Generated Jan 21, 2014 11:35:29 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ResistenciasRompimiento generated by hbm2java
 */
@Entity
@Table(name="resistencias_rompimiento"
    ,catalog="madr_bd10"
)
public class ResistenciasRompimiento  implements java.io.Serializable {


     private Integer idResRom;
     private String nombreResRom;

    public ResistenciasRompimiento() {
    }
    
    public ResistenciasRompimiento(Integer idResRom) {
        this.idResRom = idResRom;
    }

    public ResistenciasRompimiento(String nombreResRom) {
       this.nombreResRom = nombreResRom;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_res_rom", unique=true, nullable=false)
    public Integer getIdResRom() {
        return this.idResRom;
    }
    
    public void setIdResRom(Integer idResRom) {
        this.idResRom = idResRom;
    }
    
    @Column(name="nombre_res_rom", length=45)
    public String getNombreResRom() {
        return this.nombreResRom;
    }
    
    public void setNombreResRom(String nombreResRom) {
        this.nombreResRom = nombreResRom;
    }

}


