package org.aepscolombia.platform.models.entity;
// Generated Apr 8, 2014 9:37:27 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ResidualsClasification generated by hbm2java
 */
@Entity
@Table(name="residuals_clasification")
public class ResidualsClasification  implements java.io.Serializable {


     private int idResCla;
     private String nameResCla;
     private boolean statusResCla;
     private IdiomCountry countryResCla;

    public ResidualsClasification() {
    }

	
    public ResidualsClasification(int idResCla, String nameResCla, boolean statusResCla) {
        this.idResCla = idResCla;
        this.nameResCla = nameResCla;
        this.statusResCla = statusResCla;
    }
   
     @Id 
    
    @Column(name="id_res_cla", unique=true, nullable=false)
    public int getIdResCla() {
        return this.idResCla;
    }
    
    public void setIdResCla(int idResCla) {
        this.idResCla = idResCla;
    }
    
    @Column(name="name_res_cla", nullable=false, length=45)
    public String getNameResCla() {
        return this.nameResCla;
    }
    
    public void setNameResCla(String nameResCla) {
        this.nameResCla = nameResCla;
    }
    
    @Column(name="status_res_cla", nullable=false)
    public boolean isStatusResCla() {
        return this.statusResCla;
    }
    
    public void setStatusResCla(boolean statusResCla) {
        this.statusResCla = statusResCla;
    }
    
    @ManyToOne
    @JoinColumn(name="country_res_cla")
    public IdiomCountry getCountryResCla() {
        return this.countryResCla;
    }
    
    public void setCountryResCla(IdiomCountry countryResCla) {
        this.countryResCla = countryResCla;
    }    

}


