package org.aepscolombia.platform.models.entity;
// Generated Apr 8, 2014 9:37:27 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RiceSystem generated by hbm2java
 */
@Entity
@Table(name="rice_system")
public class RiceSystem  implements java.io.Serializable {


     private Integer idRieSys;
     private String nameRieSys;
     private Boolean statusRieSys;
     private IdiomCountry countryRieSys;

    public RiceSystem() {
    }

    public RiceSystem(String nameRieSys, Boolean statusRieSys) {
       this.nameRieSys = nameRieSys;
       this.statusRieSys = statusRieSys;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_rie_sys", unique=true, nullable=false)
    public Integer getIdRieSys() {
        return this.idRieSys;
    }
    
    public void setIdRieSys(Integer idRieSys) {
        this.idRieSys = idRieSys;
    }
    
    @Column(name="name_rie_sys", length=45)
    public String getNameRieSys() {
        return this.nameRieSys;
    }
    
    public void setNameRieSys(String nameRieSys) {
        this.nameRieSys = nameRieSys;
    }
    
    @Column(name="status_rie_sys")
    public Boolean getStatusRieSys() {
        return this.statusRieSys;
    }
    
    public void setStatusRieSys(Boolean statusRieSys) {
        this.statusRieSys = statusRieSys;
    }
    
    @ManyToOne
    @JoinColumn(name="country_rie_sys")
    public IdiomCountry getCountryRieSys() {
        return this.countryRieSys;
    }
    
    public void setCountryRieSys(IdiomCountry countryRieSys) {
        this.countryRieSys = countryRieSys;
    }

}


