package org.aepscolombia.platform.models.entity;
// Generated Apr 8, 2014 9:37:27 AM by Hibernate Tools 3.2.1.GA

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SeedsOrigins generated by hbm2java
 */
@Entity
@Table(name="seeds_origins"
    ,catalog="madr_bd13"
)
public class SeedsOrigins  implements java.io.Serializable {


     private Integer idSeeOri;
     private String nameSeeOri;
     private boolean statusSeeOri;

    public SeedsOrigins() {
    }

	
    public SeedsOrigins(String nameSeeOri, boolean statusSeeOri) {
        this.nameSeeOri = nameSeeOri;
        this.statusSeeOri = statusSeeOri;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_see_ori", unique=true, nullable=false)
    public Integer getIdSeeOri() {
        return this.idSeeOri;
    }
    
    public void setIdSeeOri(Integer idSeeOri) {
        this.idSeeOri = idSeeOri;
    }
    
    @Column(name="name_see_ori", nullable=false, length=45)
    public String getNameSeeOri() {
        return this.nameSeeOri;
    }
    
    public void setNameSeeOri(String nameSeeOri) {
        this.nameSeeOri = nameSeeOri;
    }
    
    @Column(name="status_see_ori", nullable=false)
    public boolean isStatusSeeOri() {
        return this.statusSeeOri;
    }
    
    public void setStatusSeeOri(boolean statusSeeOri) {
        this.statusSeeOri = statusSeeOri;
    }

}


