package org.aepscolombia.platform.models.entity;
// Generated Jan 21, 2014 11:35:29 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SeedsInoculations generated by hbm2java
 */
@Entity
@Table(name="seeds_inoculations"
    ,catalog="madr_bd10"
)
public class SeedsInoculations  implements java.io.Serializable {


     private int idSeeIno;
     private String nameSeeIno;

    public SeedsInoculations() {
    }

	
    public SeedsInoculations(int idSeeIno, String nameSeeIno) {
        this.idSeeIno = idSeeIno;
        this.nameSeeIno = nameSeeIno;
    }
   
     @Id 
    
    @Column(name="id_see_ino", unique=true, nullable=false)
    public int getIdSeeIno() {
        return this.idSeeIno;
    }
    
    public void setIdSeeIno(int idSeeIno) {
        this.idSeeIno = idSeeIno;
    }
    
    @Column(name="name_see_ino", nullable=false, length=45)
    public String getNameSeeIno() {
        return this.nameSeeIno;
    }
    
    public void setNameSeeIno(String nameSeeIno) {
        this.nameSeeIno = nameSeeIno;
    }

}


