package org.aepscolombia.platform.models.entity;
// Generated Apr 8, 2014 9:37:27 AM by Hibernate Tools 3.2.1.GA

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SowingTypes generated by hbm2java
 */
@Entity
@Table(name="sowing_types")
public class SowingTypes  implements java.io.Serializable {


     private Integer idSowTyp;
     private String nameSowTyp;
     private boolean statusSowTyp;
     private IdiomCountry countrySowTyp;

    public SowingTypes() {
    }
    
    public SowingTypes(Integer idSowTyp) {
        this.idSowTyp=idSowTyp;
    }

	
    public SowingTypes(String nameSowTyp, boolean statusSowTyp) {
        this.nameSowTyp = nameSowTyp;
        this.statusSowTyp = statusSowTyp;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_sow_typ", unique=true, nullable=false)
    public Integer getIdSowTyp() {
        return this.idSowTyp;
    }
    
    public void setIdSowTyp(Integer idSowTyp) {
        this.idSowTyp = idSowTyp;
    }
    
    @Column(name="name_sow_typ", nullable=false, length=45)
    public String getNameSowTyp() {
        return this.nameSowTyp;
    }
    
    public void setNameSowTyp(String nameSowTyp) {
        this.nameSowTyp = nameSowTyp;
    }
    
    @Column(name="status_sow_typ", nullable=false)
    public boolean isStatusSowTyp() {
        return this.statusSowTyp;
    }
    
    public void setStatusSowTyp(boolean statusSowTyp) {
        this.statusSowTyp = statusSowTyp;
    }
    
    @ManyToOne
    @JoinColumn(name="country_sow_typ")
    public IdiomCountry getCountrySowTyp() {
        return this.countrySowTyp;
    }
    
    public void setCountrySowTyp(IdiomCountry countrySowTyp) {
        this.countrySowTyp = countrySowTyp;
    }

}


