package org.aepscolombia.platform.models.entity;
// Generated Apr 8, 2014 9:37:27 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sowing generated by hbm2java
 */
@Entity
@Table(name="sowing"
    ,catalog="madr_bd13"
)
public class Sowing  implements java.io.Serializable {


     private Integer idSow;
     private Genotypes genotypes;
     private DoseUnits doseUnits;
     private TreatmentTypes treatmentTypes;
     private ChemicalsSowing chemicalsSowing;
     private ProductionEvents productionEvents;
     private SowingTypes sowingTypes;
     private GenotypesSowing genotypesSowing;
     private SeedsOrigins seedsOrigins;
     private Date dateSow;
     private Integer seedsNumberSow;
     private boolean treatedSeedsSow;
     private String reasonTreatmentSow;
     private Double seedTreatmentDosisSow;
     private Double furrowsDistanceSow;
     private Double sitesDistanceSow;
     private String freeSeedOriginSow;
     private String otherGenotypeSow;
     private String otherChemicalUsedSow;
     private Boolean status;
     private Integer createdBy;

    public Sowing() {
    }

	
    public Sowing(ProductionEvents productionEvents, SowingTypes sowingTypes, Date dateSow, boolean treatedSeedsSow) {
        this.productionEvents = productionEvents;
        this.sowingTypes = sowingTypes;
        this.dateSow = dateSow;
        this.treatedSeedsSow = treatedSeedsSow;
    }
    public Sowing(Genotypes genotypes, DoseUnits doseUnits, TreatmentTypes treatmentTypes, ChemicalsSowing chemicalsSowing, ProductionEvents productionEvents, SowingTypes sowingTypes, GenotypesSowing genotypesSowing, SeedsOrigins seedsOrigins, Date dateSow, Integer seedsNumberSow, boolean treatedSeedsSow, String reasonTreatmentSow, Double seedTreatmentDosisSow, Double furrowsDistanceSow, Double sitesDistanceSow, String freeSeedOriginSow, String otherGenotypeSow, String otherChemicalUsedSow, Boolean status, Integer createdBy) {
       this.genotypes = genotypes;
       this.doseUnits = doseUnits;
       this.treatmentTypes = treatmentTypes;
       this.chemicalsSowing = chemicalsSowing;
       this.productionEvents = productionEvents;
       this.sowingTypes = sowingTypes;
       this.genotypesSowing = genotypesSowing;
       this.seedsOrigins = seedsOrigins;
       this.dateSow = dateSow;
       this.seedsNumberSow = seedsNumberSow;
       this.treatedSeedsSow = treatedSeedsSow;
       this.reasonTreatmentSow = reasonTreatmentSow;
       this.seedTreatmentDosisSow = seedTreatmentDosisSow;
       this.furrowsDistanceSow = furrowsDistanceSow;
       this.sitesDistanceSow = sitesDistanceSow;
       this.freeSeedOriginSow = freeSeedOriginSow;
       this.otherGenotypeSow = otherGenotypeSow;
       this.otherChemicalUsedSow = otherChemicalUsedSow;
       this.status = status;
       this.createdBy = createdBy;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_sow", unique=true, nullable=false)
    public Integer getIdSow() {
        return this.idSow;
    }
    
    public void setIdSow(Integer idSow) {
        this.idSow = idSow;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="genotype_sow")
    public Genotypes getGenotypes() {
        return this.genotypes;
    }
    
    public void setGenotypes(Genotypes genotypes) {
        this.genotypes = genotypes;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dose_unit_sow")
    public DoseUnits getDoseUnits() {
        return this.doseUnits;
    }
    
    public void setDoseUnits(DoseUnits doseUnits) {
        this.doseUnits = doseUnits;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="seed_treatment_type_sow")
    public TreatmentTypes getTreatmentTypes() {
        return this.treatmentTypes;
    }
    
    public void setTreatmentTypes(TreatmentTypes treatmentTypes) {
        this.treatmentTypes = treatmentTypes;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="used_chemical_sow")
    public ChemicalsSowing getChemicalsSowing() {
        return this.chemicalsSowing;
    }
    
    public void setChemicalsSowing(ChemicalsSowing chemicalsSowing) {
        this.chemicalsSowing = chemicalsSowing;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_production_event_sow", nullable=false)
    public ProductionEvents getProductionEvents() {
        return this.productionEvents;
    }
    
    public void setProductionEvents(ProductionEvents productionEvents) {
        this.productionEvents = productionEvents;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sowing_type_sow", nullable=false)
    public SowingTypes getSowingTypes() {
        return this.sowingTypes;
    }
    
    public void setSowingTypes(SowingTypes sowingTypes) {
        this.sowingTypes = sowingTypes;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="genotyte_type_seed_sow")
    public GenotypesSowing getGenotypesSowing() {
        return this.genotypesSowing;
    }
    
    public void setGenotypesSowing(GenotypesSowing genotypesSowing) {
        this.genotypesSowing = genotypesSowing;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="seed_origin_sow")
    public SeedsOrigins getSeedsOrigins() {
        return this.seedsOrigins;
    }
    
    public void setSeedsOrigins(SeedsOrigins seedsOrigins) {
        this.seedsOrigins = seedsOrigins;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_sow", nullable=false, length=19)
    public Date getDateSow() {
        return this.dateSow;
    }
    
    public void setDateSow(Date dateSow) {
        this.dateSow = dateSow;
    }
    
    @Column(name="seeds_number_sow")
    public Integer getSeedsNumberSow() {
        return this.seedsNumberSow;
    }
    
    public void setSeedsNumberSow(Integer seedsNumberSow) {
        this.seedsNumberSow = seedsNumberSow;
    }
    
    @Column(name="treated_seeds_sow", nullable=false)
    public boolean isTreatedSeedsSow() {
        return this.treatedSeedsSow;
    }
    
    public void setTreatedSeedsSow(boolean treatedSeedsSow) {
        this.treatedSeedsSow = treatedSeedsSow;
    }
    
    @Column(name="reason_treatment_sow", length=10)
    public String getReasonTreatmentSow() {
        return this.reasonTreatmentSow;
    }
    
    public void setReasonTreatmentSow(String reasonTreatmentSow) {
        this.reasonTreatmentSow = reasonTreatmentSow;
    }
    
    @Column(name="seed_treatment_dosis_sow", precision=22, scale=0)
    public Double getSeedTreatmentDosisSow() {
        return this.seedTreatmentDosisSow;
    }
    
    public void setSeedTreatmentDosisSow(Double seedTreatmentDosisSow) {
        this.seedTreatmentDosisSow = seedTreatmentDosisSow;
    }
    
    @Column(name="furrows_distance_sow", precision=22, scale=0)
    public Double getFurrowsDistanceSow() {
        return this.furrowsDistanceSow;
    }
    
    public void setFurrowsDistanceSow(Double furrowsDistanceSow) {
        this.furrowsDistanceSow = furrowsDistanceSow;
    }
    
    @Column(name="sites_distance_sow", precision=22, scale=0)
    public Double getSitesDistanceSow() {
        return this.sitesDistanceSow;
    }
    
    public void setSitesDistanceSow(Double sitesDistanceSow) {
        this.sitesDistanceSow = sitesDistanceSow;
    }
    
    @Column(name="free_seed_origin_sow", length=14)
    public String getFreeSeedOriginSow() {
        return this.freeSeedOriginSow;
    }
    
    public void setFreeSeedOriginSow(String freeSeedOriginSow) {
        this.freeSeedOriginSow = freeSeedOriginSow;
    }
    
    @Column(name="other_genotype_sow", length=65535)
    public String getOtherGenotypeSow() {
        return this.otherGenotypeSow;
    }
    
    public void setOtherGenotypeSow(String otherGenotypeSow) {
        this.otherGenotypeSow = otherGenotypeSow;
    }
    
    @Column(name="other_chemical_used_sow", length=65535)
    public String getOtherChemicalUsedSow() {
        return this.otherChemicalUsedSow;
    }
    
    public void setOtherChemicalUsedSow(String otherChemicalUsedSow) {
        this.otherChemicalUsedSow = otherChemicalUsedSow;
    }
    
    @Column(name="status")
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    
    @Column(name="created_by")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }




}


