package org.aepscolombia.platform.models.entity;
// Generated Jan 21, 2014 11:35:29 AM by Hibernate Tools 3.2.1.GA

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SowingTypes generated by hbm2java
 */
@Entity
@Table(name="sowing_types"
    ,catalog="madr_bd11"
)
public class SowingTypes  implements java.io.Serializable {


     private Integer idSowTyp;
     private String nameSowTyp;
     private boolean statusSowType;

    public SowingTypes() {
    }

	
    public SowingTypes(String nameSowTyp, boolean statusSowType) {
        this.nameSowTyp = nameSowTyp;
        this.statusSowType = statusSowType;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_sow_typ", unique=true, nullable=false)
    public Integer getIdSowTyp() {
        return this.idSowTyp;
    }
    
    public void setIdSowTyp(Integer idSowTyp) {
        this.idSowTyp = idSowTyp;
    }
    
    @Column(name="name_sow_typ", nullable=false, length=45)
    public String getNameSowTyp() {
        return this.nameSowTyp;
    }
    
    public void setNameSowTyp(String nameSowTyp) {
        this.nameSowTyp = nameSowTyp;
    }
    
    @Column(name="status_sow_type", nullable=false)
    public boolean isStatusSowType() {
        return this.statusSowType;
    }
    
    public void setStatusSowType(boolean statusSowType) {
        this.statusSowType = statusSowType;
    }

}


