package org.aepscolombia.platform.models.entity;
// Generated Jan 21, 2014 11:35:29 AM by Hibernate Tools 3.2.1.GA

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TargetsTypes generated by hbm2java
 */
@Entity
@Table(name="targets_types")
public class TargetsTypes  implements java.io.Serializable {


     private Integer idTarTyp;
     private String nameTarTyp;
     private Boolean statusTarTyp;
     private IdiomCountry countryTarTyp;

    public TargetsTypes() {
    }

	
    public TargetsTypes(String nameTarTyp) {
        this.nameTarTyp = nameTarTyp;
    }
    public TargetsTypes(String nameTarTyp, Boolean statusTarTyp) {
       this.nameTarTyp = nameTarTyp;
       this.statusTarTyp = statusTarTyp;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_tar_typ", unique=true, nullable=false)
    public Integer getIdTarTyp() {
        return this.idTarTyp;
    }
    
    public void setIdTarTyp(Integer idTarTyp) {
        this.idTarTyp = idTarTyp;
    }
    
    @Column(name="name_tar_typ", nullable=false, length=45)
    public String getNameTarTyp() {
        return this.nameTarTyp;
    }
    
    public void setNameTarTyp(String nameTarTyp) {
        this.nameTarTyp = nameTarTyp;
    }
    
    @Column(name="status_tar_typ")
    public Boolean getStatusTarTyp() {
        return this.statusTarTyp;
    }
    
    public void setStatusTarTyp(Boolean statusTarTyp) {
        this.statusTarTyp = statusTarTyp;
    }
    
    @ManyToOne
    @JoinColumn(name="country_tar_typ")
    public IdiomCountry getCountryTarTyp() {
        return this.countryTarTyp;
    }
    
    public void setCountryTarTyp(IdiomCountry countryTarTyp) {
        this.countryTarTyp = countryTarTyp;
    }
    
}


