package org.aepscolombia.platform.models.entity;
// Generated Jan 21, 2014 11:35:29 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TreatmentTypes generated by hbm2java
 */
@Entity
@Table(name="treatment_types"
    ,catalog="madr_bd10"
)
public class TreatmentTypes  implements java.io.Serializable {


     private Integer idTreTyp;
     private String nameTreTyp;
     private boolean statusTreTyp;

    public TreatmentTypes() {
    }

	
    public TreatmentTypes(String nameTreTyp, boolean statusTreTyp) {
        this.nameTreTyp = nameTreTyp;
        this.statusTreTyp = statusTreTyp;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_tre_typ", unique=true, nullable=false)
    public Integer getIdTreTyp() {
        return this.idTreTyp;
    }
    
    public void setIdTreTyp(Integer idTreTyp) {
        this.idTreTyp = idTreTyp;
    }
    
    @Column(name="name_tre_typ", nullable=false, length=45)
    public String getNameTreTyp() {
        return this.nameTreTyp;
    }
    
    public void setNameTreTyp(String nameTreTyp) {
        this.nameTreTyp = nameTreTyp;
    }
    
    @Column(name="status_tre_typ", nullable=false)
    public boolean isStatusTreTyp() {
        return this.statusTreTyp;
    }
    
    public void setStatusTreTyp(boolean statusTreTyp) {
        this.statusTreTyp = statusTreTyp;
    }

}


