package org.aepscolombia.platform.models.entity;
// Generated Apr 8, 2014 9:37:27 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UseIrrigation generated by hbm2java
 */
@Entity
@Table(name="use_irrigation")
public class UseIrrigation  implements java.io.Serializable {


     private Integer idUseIrr;
     private String nameUseIrr;
     private Boolean statusUseIrr;

    public UseIrrigation() {
    }

    public UseIrrigation(String nameUseIrr, Boolean statusUseIrr) {
       this.nameUseIrr = nameUseIrr;
       this.statusUseIrr = statusUseIrr;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_use_irr", unique=true, nullable=false)
    public Integer getIdUseIrr() {
        return this.idUseIrr;
    }
    
    public void setIdUseIrr(Integer idUseIrr) {
        this.idUseIrr = idUseIrr;
    }
    
    @Column(name="name_use_irr", length=45)
    public String getNameUseIrr() {
        return this.nameUseIrr;
    }
    
    public void setNameUseIrr(String nameUseIrr) {
        this.nameUseIrr = nameUseIrr;
    }
    
    @Column(name="status_use_irr")
    public Boolean getStatusUseIrr() {
        return this.statusUseIrr;
    }
    
    public void setStatusUseIrr(Boolean statusUseIrr) {
        this.statusUseIrr = statusUseIrr;
    }

}


