package org.aepscolombia.platform.models.entity;
// Generated Jan 21, 2014 11:35:29 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserEntity generated by hbm2java
 */
@Entity
@Table(name="user_entity"
    ,catalog="madr_bd11"
)
public class UserEntity  implements java.io.Serializable {


     private Integer idUsrEnt;
     private Entities entities;
     private Users users;
     private Integer idProjectUsrEnt;
     private boolean statusUsrEnt;

    public UserEntity() {
    }

	
    public UserEntity(Entities entities, Users users, boolean statusUsrEnt) {
        this.entities = entities;
        this.users = users;
        this.statusUsrEnt = statusUsrEnt;
    }
    public UserEntity(Entities entities, Users users, Integer idProjectUsrEnt, boolean statusUsrEnt) {
       this.entities = entities;
       this.users = users;
       this.idProjectUsrEnt = idProjectUsrEnt;
       this.statusUsrEnt = statusUsrEnt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_usr_ent", unique=true, nullable=false)
    public Integer getIdUsrEnt() {
        return this.idUsrEnt;
    }
    
    public void setIdUsrEnt(Integer idUsrEnt) {
        this.idUsrEnt = idUsrEnt;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_entity_usr_ent", nullable=false)
    public Entities getEntities() {
        return this.entities;
    }
    
    public void setEntities(Entities entities) {
        this.entities = entities;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_user_usr_ent", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    
    @Column(name="id_project_usr_ent")
    public Integer getIdProjectUsrEnt() {
        return this.idProjectUsrEnt;
    }
    
    public void setIdProjectUsrEnt(Integer idProjectUsrEnt) {
        this.idProjectUsrEnt = idProjectUsrEnt;
    }
    
    @Column(name="status_usr_ent", nullable=false)
    public boolean isStatusUsrEnt() {
        return this.statusUsrEnt;
    }
    
    public void setStatusUsrEnt(boolean statusUsrEnt) {
        this.statusUsrEnt = statusUsrEnt;
    }




}


