package org.aepscolombia.platform.models.entity;
// Generated Jan 21, 2014 11:35:29 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Weeds generated by hbm2java
 */
@Entity
@Table(name="weeds"
    ,catalog="madr_bd11"
)
public class Weeds  implements java.io.Serializable {


     private Integer idWee;
     private String nameWee;
     private boolean statusWee;

    public Weeds() {
    }

	
    public Weeds(String nameWee, boolean statusWee) {
        this.nameWee = nameWee;
        this.statusWee = statusWee;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_wee", unique=true, nullable=false)
    public Integer getIdWee() {
        return this.idWee;
    }
    
    public void setIdWee(Integer idWee) {
        this.idWee = idWee;
    }
    
    @Column(name="name_wee", nullable=false, length=100)
    public String getNameWee() {
        return this.nameWee;
    }
    
    public void setNameWee(String nameWee) {
        this.nameWee = nameWee;
    }
    
    @Column(name="status_wee", nullable=false)
    public boolean isStatusWee() {
        return this.statusWee;
    }
    
    public void setStatusWee(boolean statusWee) {
        this.statusWee = statusWee;
    }

}


